DROP TABLE IF EXISTS ST_PRODUCT_INFO;

CREATE TABLE ST_PRODUCT_INFO
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY    CHAR(1),
    NAME        VARCHAR(128),
    PRICE       INT,
    QUANTITY    INT,
    CREATE_DTM  VARCHAR(14)
);

    -- INSERT INTO ST_PRODUCT_INFO(ID, CATEGORY, NAME, PRICE, QUANTITY)
    -- VALUES (1, '1', 'name1', 200000, 5);
    --
    -- INSERT INTO ST_PRODUCT_INFO(CATEGORY, NAME, PRICE, QUANTITY)
    -- VALUES ('2', 'name2', 150000, 10);
