DROP TABLE IF EXISTS ST_PRODUCT_INFO;

CREATE TABLE ST_PRODUCT_INFO
(
    ID      INT PRIMARY KEY AUTO_INCREMENT,
    NAME    VARCHAR(128),
    PRICE   INT
);

INSERT INTO ST_PRODUCT_INFO(ID, NAME, PRICE)
VALUES (1, 'name1', 200000);

INSERT INTO ST_PRODUCT_INFO(ID, NAME, PRICE)
VALUES (2, 'name2', 150000);
